pipelinetemplatename: pipeline-template-plan-to-deploy-v2 
pipelinename: DockerTriggerTest1
application: my-app-boarding1
variables: 
  account: dev-kube-v2-account
  cloudprovider: kubernetes
  containerimage: docker.io/opsmx11/restapp:restapp-test-1.0
  containername: restapp
  manifest-namespace: sudhakar
  replicas: 1
triggers:
  - account: my-docker-registry
    enabled: true
    organization: opsmx11
    registry: index.docker.io
    repository: opsmx11/restapp
    type: docker
    
